Repository WormBase/names, pull requests merged in 2019-05, with the labels that each got.

#211 Update BiotypeSelect.js
  client/src/components/elements/BiotypeSelect.js
Labels: UI, bug

#222 Implemented ability to bypass nomenclature validation.
  src/wormbase/names/validation.clj
  src/wormbase/specs/common.clj
  test/integration/test_batch_new_gene.clj
  test/integration/test_new.clj
Labels: feature

#221 Feature/current status
  README.md
  src/wormbase/names/util.clj
  src/wormbase/names/variation.clj
  test/integration/test_update.clj
Labels: enhancement, feature
